#for_mysql

FROM mysql:5.7

MAINTAINER <olegrx144@gmail.com>

EXPOSE 3306

RUN apt-get update

ENV MYSQL_ROOT_PASSWORD="oleg"
ENV MYSQL_DATABASE=tsviki
ENV MYSQL_USER=8bit
ENV MYSQL_DATABASE_PASSWORD="password"


