#for_mysql

FROM mysql:5.7

MAINTAINER <ruddstoner@gmail.com>

EXPOSE 3306

RUN apt-get update

ENV MYSQL_ROOT_PASSWORD="09122000Vit"
ENV MYSQL_DATABASE=rudyk
ENV MYSQL_USER=vitalik
ENV MYSQL_DATABASE_PASSWORD="password"


